GET http://localhost:5083/games

###
GET http://localhost:5083/games/19

###
//If request a game which is not available
GET http://localhost:5083/games/2


###
POST http://localhost:5083/games
Content-Type: application/json

{
    "name" : "Marvels Spiderman 2",
    "genreId" : 2,
    "price" : 99.00,
    "releaseDate" : "2023-08-25"
}

###
PUT http://localhost:5083/games/2
Content-Type: application/json

{
    "name" : "MEtal Gear Solid 2",
    "genreId" : 2,
    "price" : 5.99,
    "releaseDate" : "2008-02-25"
}

###
///PUT request for a id which is not present
PUT http://localhost:5083/games/22
Content-Type: application/json

{
    "name" : "Street Fighter II Turbo",
    "genre" : "Kids and Family",
    "price" : 59.99,
    "releaseDate" : "2011-11-18"
}
###
DELETE http://localhost:5083/games/6